/**
 * Derived from @ultraviolet/icons DistributedDataLabProductIcon (Scaleway, Apache-2.0).
 * Generated by scripts/extract-uv-icons.ts — do not edit by hand.
 */
import type { UvIconProps } from "./types";

export const DistributedDataLabIcon: React.FC<UvIconProps> = ({ size = 64, style }) => (
  <svg
    fill="none"
    height={size}
    style={style}
    viewBox="0 0 64 64"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
  >
    <g className="Distributed Data Lab">
      <g className="Container-Registry">
        <g className=".Square">
          <path
            fill="var(--uv-weak)"
            d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
            className="fillWeak"
          />
        </g>
        <g fill="var(--uv-strong)" fillRule="evenodd" className="fillStrong" clipRule="evenodd">
          <path d="M44 31.901a1 1 0 0 1 1-1h12.79a1 1 0 1 1 0 2H45a1 1 0 0 1-1-1" className="fillStrong" />
          <path
            d="M53.502 27.813a1 1 0 0 1 1.4-.2l4.651 3.489a1 1 0 0 1 0 1.6l-4.65 3.488a1 1 0 0 1-1.2-1.6l3.584-2.689-3.585-2.688a1 1 0 0 1-.2-1.4"
            className="fillStrong"
          />
        </g>
        <g fill="var(--uv-strong)" fillRule="evenodd" className="fillStrong" clipRule="evenodd">
          <path
            d="M35.741 28.154a1 1 0 0 1 0-1.414l10.465-10.465a1 1 0 0 1 1.414 1.414L37.155 28.154a1 1 0 0 1-1.414 0"
            className="fillStrong"
          />
          <path
            d="M41.306 16.844a1 1 0 0 1 .849-1.131l5.755-.822a1 1 0 0 1 1.132 1.131l-.822 5.756a1 1 0 0 1-1.98-.283l.633-4.436-4.435.634a1 1 0 0 1-1.132-.849"
            className="fillStrong"
          />
        </g>
        <g fill="var(--uv-strong)" fillRule="evenodd" className="fillStrong" clipRule="evenodd">
          <path
            d="M35.741 35.192a1 1 0 0 0 0 1.414L46.206 47.07a1 1 0 0 0 1.414-1.414L37.155 35.192a1 1 0 0 0-1.414 0"
            className="fillStrong"
          />
          <path
            d="M41.306 46.501a1 1 0 0 0 .849 1.132l5.755.822a1 1 0 0 0 1.132-1.131l-.822-5.756a1 1 0 0 0-1.98.283l.633 4.435-4.435-.633a1 1 0 0 0-1.132.848"
            className="fillStrong"
          />
        </g>
        <path
          fill="var(--uv-base)"
          fillRule="evenodd"
          d="M31.28 18.826c.42-1.131 2.02-1.131 2.44 0l3.205 8.663 8.662 3.205c1.131.419 1.131 2.02 0 2.438l-8.663 3.206L33.72 45c-.419 1.132-2.02 1.132-2.438 0l-3.205-8.662-8.663-3.206c-1.131-.418-1.131-2.02 0-2.438l8.663-3.205 3.205-8.663Zm1.22 2.469-2.66 7.19a1.3 1.3 0 0 1-.769.768l-7.19 2.66 7.19 2.66a1.3 1.3 0 0 1 .768.769l2.661 7.19 2.66-7.19a1.3 1.3 0 0 1 .769-.768l7.19-2.66-7.19-2.661a1.3 1.3 0 0 1-.769-.768z"
          className="fill"
          clipRule="evenodd"
        />
        <g className="fillStrong">
          <path
            fill="var(--uv-strong)"
            fillRule="evenodd"
            d="M14.475 32.227a1 1 0 0 0-1-1H6a1 1 0 1 0 0 2h7.475a1 1 0 0 0 1-1m4.153-5.814a1 1 0 0 0-1-1h-7.475a1 1 0 0 0 0 2h7.475a1 1 0 0 0 1-1m0 11.628a1 1 0 0 0-1-1h-7.475a1 1 0 0 0 0 2h7.475a1 1 0 0 0 1-1"
            className="fillStrong"
            clipRule="evenodd"
          />
        </g>
      </g>
    </g>
  </svg>
);
