/**
 * Derived from @ultraviolet/icons MonitoringProductIcon (Scaleway, Apache-2.0).
 * Generated by scripts/extract-uv-icons.ts — do not edit by hand.
 */
import type { UvIconProps } from "./types";

export const MonitoringIcon: React.FC<UvIconProps> = ({ size = 64, style }) => (
  <svg
    fill="none"
    height={size}
    style={style}
    viewBox="0 0 64 64"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
  >
    <g className="Monitoring">
      <g className="Monitoring-icon" clipPath="url(#a)">
        <g className=".Square">
          <path
            fill="var(--uv-weak)"
            d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
            className="fillWeak"
          />
        </g>
        <g fillRule="evenodd" className="Icon" clipRule="evenodd">
          <path
            fill="var(--uv-base)"
            d="M16.87 15h30.26A5.87 5.87 0 0 1 53 20.87v23.26A5.87 5.87 0 0 1 47.13 50H16.87A5.87 5.87 0 0 1 11 44.13V20.87A5.87 5.87 0 0 1 16.87 15m30.26 2H16.87A3.87 3.87 0 0 0 13 20.87V23h38v-2.13A3.87 3.87 0 0 0 47.13 17M13 44.13V25h38v19.13A3.87 3.87 0 0 1 47.13 48H16.87A3.87 3.87 0 0 1 13 44.13M46.498 19H41l-.117.007A1 1 0 0 0 41 21h5.498l.116-.007A1 1 0 0 0 46.498 19"
            className="fill"
          />
          <path
            fill="var(--uv-strong)"
            d="M41 30a6 6 0 1 1 0 12 6 6 0 0 1 0-12m-1 2.126a4.002 4.002 0 1 0 2.848 7.422l-2.591-2.879a1 1 0 0 1-.25-.546L40 36zm2 0v3.49l2.335 2.594A4.002 4.002 0 0 0 42 32.126m-22.007 2.757A1 1 0 0 0 18 35v6.397l.007.117A1 1 0 0 0 20 41.397V35zM23 30a1 1 0 0 1 .993.883L24 31v10.397a1 1 0 0 1-1.993.117L22 41.397V31a1 1 0 0 1 1-1m4.993.883A1 1 0 0 0 26 31v10.397l.007.117A1 1 0 0 0 28 41.397V31zM31 37a1 1 0 0 1 .993.883L32 38v3.397a1 1 0 0 1-1.993.117L30 41.397V38a1 1 0 0 1 1-1"
            className="fillStrong"
          />
        </g>
      </g>
    </g>
    <defs>
      <clipPath id="a" className="a">
        <path fill="var(--uv-weak)" d="M0 0h64v64H0z" />
      </clipPath>
    </defs>
  </svg>
);
