/**
 * Derived from @ultraviolet/icons QueueingProductIcon (Scaleway, Apache-2.0).
 * Generated by scripts/extract-uv-icons.ts — do not edit by hand.
 */
import type { UvIconProps } from "./types";

export const QueueingIcon: React.FC<UvIconProps> = ({ size = 64, style }) => (
  <svg
    fill="none"
    height={size}
    style={style}
    viewBox="0 0 64 64"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
  >
    <g className="Queuing">
      <g className="icon" clipPath="url(#a)">
        <g className=".Square">
          <path
            fill="var(--uv-weak)"
            d="M0 16C0 7.163 7.163 0 16 0h32c8.837 0 16 7.163 16 16v32c0 8.837-7.163 16-16 16H16C7.163 64 0 56.837 0 48z"
            className="fillWeak"
          />
        </g>
        <g className="icon">
          <path
            fill="var(--uv-strong)"
            d="M33 19a1 1 0 0 0-1 1v24a1 1 0 1 0 2 0V20a1 1 0 0 0-1-1m-19 4a1 1 0 1 1 2 0 1 1 0 0 1-2 0m14 0a1 1 0 1 1 2 0 1 1 0 0 1-2 0m-3 8a1 1 0 1 0 0 2 1 1 0 0 0 0-2m3 1a1 1 0 1 1 2 0 1 1 0 0 1-2 0m-13 8a1 1 0 1 0 0 2 1 1 0 0 0 0-2m3 1a1 1 0 1 1 2 0 1 1 0 0 1-2 0"
            className="fillStrong"
          />
          <path
            fill="var(--uv-base)"
            d="M18 23a1 1 0 0 1 1-1h6a1 1 0 1 1 0 2h-6a1 1 0 0 1-1-1m4 18a1 1 0 0 1 1-1h6a1 1 0 1 1 0 2h-6a1 1 0 0 1-1-1m-7-10a1 1 0 1 0 0 2h6a1 1 0 1 0 0-2zm22-12a1 1 0 0 0-1 1v24a1 1 0 1 0 2 0V33h8.9l-2.593 2.593a1 1 0 0 0 1.414 1.414l4.243-4.243a1 1 0 0 0 .275-.898 1 1 0 0 0-.29-.616l-4.242-4.243a1 1 0 0 0-1.414 1.414L46.872 31H38V20a1 1 0 0 0-1-1"
            className="fill"
          />
        </g>
      </g>
    </g>
  </svg>
);
