/**
 * Turns a Natural Earth countries GeoJSON into a compact set of SVG paths for
 * the Vox-style map scene.
 *
 * Source (110m = coarsest, plenty for a background map):
 *   https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_admin_0_countries.geojson
 *
 * Run: npx tsx scripts/build-world-map.ts <path-to.geojson>
 *
 * Coordinates are projected equirectangularly into a 1000x500 box, so the
 * component can pick any viewBox to crop (we drop Antarctica by cropping).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const W = 1000;
const H = 500;
/** Rings smaller than this (in square degrees) are dropped — small islands. */
const MIN_AREA = 2.5;

type Ring = [number, number][];

const project = ([lon, lat]: [number, number]): [number, number] => [
  Math.round((((lon + 180) / 360) * W) * 10) / 10,
  Math.round((((90 - lat) / 180) * H) * 10) / 10,
];

/** Shoelace area, used only to rank rings by size. */
const area = (ring: Ring): number => {
  let sum = 0;
  for (let i = 0; i < ring.length; i++) {
    const [x1, y1] = ring[i];
    const [x2, y2] = ring[(i + 1) % ring.length];
    sum += x1 * y2 - x2 * y1;
  }

  return Math.abs(sum / 2);
};

const toPath = (ring: Ring): string => {
  const pts = ring.map(project);
  // Drop consecutive duplicates introduced by rounding.
  const dedup = pts.filter(
    (p, i) => i === 0 || p[0] !== pts[i - 1][0] || p[1] !== pts[i - 1][1],
  );
  if (dedup.length < 3) return "";

  return `M${dedup.map(([x, y]) => `${x} ${y}`).join("L")}Z`;
};

const source = process.argv[2];
if (!source) {
  console.error("Usage: npx tsx scripts/build-world-map.ts <path-to.geojson>");
  process.exit(1);
}

const geo = JSON.parse(readFileSync(source, "utf8"));
const paths: string[] = [];

for (const feature of geo.features) {
  const name: string = feature.properties?.NAME ?? "";
  if (name === "Antarctica") continue;

  const { type, coordinates } = feature.geometry;
  const polygons: Ring[][] =
    type === "Polygon" ? [coordinates] : type === "MultiPolygon" ? coordinates : [];

  for (const polygon of polygons) {
    // Index 0 is the outer ring; holes are irrelevant at this scale.
    const ring = polygon[0] as Ring;
    if (area(ring) < MIN_AREA) continue;

    const d = toPath(ring);
    if (d) paths.push(d);
  }
}

const out = join(import.meta.dirname, "../src/vox/worldPaths.ts");
writeFileSync(
  out,
  `/**
 * Country outlines projected equirectangularly into a ${W}x${H} box.
 * Generated by scripts/build-world-map.ts from Natural Earth 110m data
 * (public domain) — do not edit by hand.
 */
export const WORLD_WIDTH = ${W};
export const WORLD_HEIGHT = ${H};

export const WORLD_PATHS: readonly string[] = ${JSON.stringify(paths, null, 0)};
`,
  "utf8",
);

console.log(`Wrote ${paths.length} rings (${Math.round(JSON.stringify(paths).length / 1024)} kB)`);
