/**
 * Extracts Scaleway Ultraviolet ProductIcon artwork into standalone, dependency-free
 * Remotion components.
 *
 * Why not import @ultraviolet/icons directly? The source components rely on
 * vanilla-extract (build-time CSS-in-JS) plus a theme provider, which would drag a
 * bundler plugin into Remotion's render pipeline. The SVG geometry is the part we
 * actually want, so we lift it verbatim and swap the baked-in Scaleway purples for
 * CSS custom properties, letting each scene retheme the same artwork at runtime.
 *
 * Source: packages/icons/src/components/ProductIcon/__generated__ (Apache-2.0)
 * Run: npx tsx scripts/extract-uv-icons.ts
 */
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";

const UV_GENERATED = join(
  import.meta.dirname,
  "../../packages/icons/src/components/ProductIcon/__generated__",
);
const OUT_DIR = join(import.meta.dirname, "../src/deep/icons");

/** Ultraviolet bakes the `primary` variant colours into the generated markup. */
const COLOR_SLOTS: Record<string, string> = {
  // fillWeak — the rounded plate behind the glyph
  "#eef": "var(--uv-weak)",
  "#f1eefc": "var(--uv-weak)",
  "#fff": "var(--uv-weak)",
  // fill — the main glyph body
  "#4f0599": "var(--uv-base)",
  "#521094": "var(--uv-base)",
  // fillStrong — accents and highlights
  "#a365f6": "var(--uv-strong)",
  "#a060f6": "var(--uv-strong)",
  "#bf95f9": "var(--uv-strong)",
};

const WANTED = [
  "ApiGateway",
  "AuditTrail",
  "Bandwidth",
  "BlockStorage",
  "Cdn",
  "Cockpit",
  "ColdStorage",
  "ComputeOptimizedInstances",
  "Containers",
  "DataWarehouse",
  "Ddos",
  "Devices",
  "DirectConnect",
  "DistributedDataLab",
  "Dns",
  "EdgeServices",
  "ElasticMetal",
  "FlexibleIp",
  "Functions",
  "GpuServers",
  "Iam",
  "Instance",
  "Kubernetes",
  "ManagedKafka",
  "MongoDb",
  "Monitoring",
  "MultiUser",
  "Nats",
  "ObjectStorage",
  "PrivateNetwork",
  "PublicGateway",
  "Queueing",
  "Rdb",
  "Redis",
  "Registry",
  "Rocket",
  "Router",
  "Server",
  "ServerlessJobs",
  "Snapshots",
  "SslCertificates",
  "User",
  "Video",
  "Vpc",
  "Waf",
  "Zone",
];

/** Pull the JSX between <Icon ...> and </Icon>, then strip one indent level. */
const extractInner = (source: string): string | null => {
  const match = source.match(/<Icon \{\.\.\.props\}[^>]*>\n([\s\S]*?)\n\s*<\/Icon>/);
  if (!match) return null;

  return match[1]
    .split("\n")
    .map((line) => (line.startsWith("    ") ? line.slice(4) : line))
    .join("\n");
};

const recolor = (markup: string): string =>
  Object.entries(COLOR_SLOTS).reduce(
    (acc, [hex, cssVar]) =>
      acc.split(`fill="${hex}"`).join(`fill="${cssVar}"`),
    markup,
  );

const available = new Set(
  readdirSync(UV_GENERATED)
    .filter((f) => f.endsWith("ProductIcon.tsx"))
    .map((f) => basename(f, "ProductIcon.tsx")),
);

mkdirSync(OUT_DIR, { recursive: true });

const emitted: string[] = [];
const missing: string[] = [];

for (const name of WANTED) {
  if (!available.has(name)) {
    missing.push(name);
    continue;
  }

  const source = readFileSync(
    join(UV_GENERATED, `${name}ProductIcon.tsx`),
    "utf8",
  );
  const inner = extractInner(source);

  if (!inner) {
    missing.push(`${name} (no <Icon> body)`);
    continue;
  }

  const component = `${name}Icon`;
  writeFileSync(
    join(OUT_DIR, `${component}.tsx`),
    `/**
 * Derived from @ultraviolet/icons ${name}ProductIcon (Scaleway, Apache-2.0).
 * Generated by scripts/extract-uv-icons.ts — do not edit by hand.
 */
import type { UvIconProps } from "./types";

export const ${component}: React.FC<UvIconProps> = ({ size = 64, style }) => (
  <svg
    fill="none"
    height={size}
    style={style}
    viewBox="0 0 64 64"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
  >
${recolor(inner)
  .split("\n")
  .map((l) => (l.trim() ? `    ${l}` : l))
  .join("\n")}
  </svg>
);
`,
    "utf8",
  );

  emitted.push(component);
}

writeFileSync(
  join(OUT_DIR, "types.ts"),
  `import type { CSSProperties } from "react";

export type UvIconProps = {
  readonly size?: number;
  readonly style?: CSSProperties;
};
`,
  "utf8",
);

writeFileSync(
  join(OUT_DIR, "index.ts"),
  `/** Generated by scripts/extract-uv-icons.ts — do not edit by hand. */
export type { UvIconProps } from "./types";
${emitted.map((c) => `export { ${c} } from "./${c}";`).join("\n")}
`,
  "utf8",
);

console.log(`Extracted ${emitted.length} icons to src/deep/icons`);
if (missing.length) console.warn(`Missing: ${missing.join(", ")}`);
