/**
 * Inlines the self-hosted fonts into a stylesheet as base64 data URIs.
 *
 * @remotion/fonts loads faces through delayRender(). That works for a still
 * and for short renders, but on the full 3600-frame job one face reproducibly
 * never cleared its handle and failed the whole render — with a 180 s timeout,
 * so it was not contention. A @font-face rule carrying a data: URI is parsed
 * with the stylesheet, before React ever mounts: there is no fetch to hang and
 * no handle to leave open.
 *
 * ~130 kB of CSS for three faces, which is a fine trade for a render that ends.
 *
 * Run: npx tsx scripts/build-fonts.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const PUBLIC = join(import.meta.dirname, "../public/fonts");
const OUT = join(import.meta.dirname, "../src/fonts.css");

const FACES = [
  { family: "Archivo Black", file: "ArchivoBlack.woff2", weight: "400" },
  { family: "Inter", file: "Inter.woff2", weight: "100 900" },
  { family: "JetBrains Mono", file: "JetBrainsMono.woff2", weight: "100 800" },
];

const css = FACES.map(({ family, file, weight }) => {
  const b64 = readFileSync(join(PUBLIC, file)).toString("base64");

  return `@font-face {
  font-family: "${family}";
  font-style: normal;
  font-weight: ${weight};
  /* block: never paint a fallback, so no frame can render with the wrong metrics */
  font-display: block;
  src: url(data:font/woff2;base64,${b64}) format("woff2");
}`;
}).join("\n\n");

writeFileSync(
  OUT,
  `/* Generated by scripts/build-fonts.ts — do not edit by hand. */\n\n${css}\n`,
  "utf8",
);

console.log(`Wrote ${FACES.length} faces, ${Math.round(css.length / 1024)} kB`);
