/**
 * Converts Ultraviolet "wire" illustrations into themeable React components.
 *
 * The published SVGs are filled pure white — they are drawn for dark surfaces,
 * so they vanish on the console *light* palette this film uses. Rewriting the
 * fills to `currentColor` lets each mount pick its own ink via CSS `color`.
 *
 * Source: packages/illustrations/src/assets/products (Scaleway, Apache-2.0)
 * Run: npx tsx scripts/build-illustrations.ts
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const SRC = join(import.meta.dirname, "../public/illustrations");
const OUT = join(import.meta.dirname, "../src/components/illustrations");

const WANTED = [
  { file: "object-storage.svg", component: "ObjectStorageIllustration" },
  { file: "block-storage.svg", component: "BlockStorageIllustration" },
  { file: "inference.svg", component: "InferenceIllustration" },
];

mkdirSync(OUT, { recursive: true });
const emitted: string[] = [];

for (const { file, component } of WANTED) {
  const raw = readFileSync(join(SRC, file), "utf8");

  const body = raw
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>\s*$/, "")
    .split('fill="#fff"')
    .join('fill="currentColor"')
    // SVG attributes that differ in JSX.
    .replace(/\bclip-path=/g, "clipPath=")
    .replace(/\bfill-rule=/g, "fillRule=")
    .replace(/\bclip-rule=/g, "clipRule=")
    .replace(/\bstroke-width=/g, "strokeWidth=")
    .replace(/\bstroke-linecap=/g, "strokeLinecap=")
    .replace(/\bstroke-linejoin=/g, "strokeLinejoin=")
    .trim();

  writeFileSync(
    join(OUT, `${component}.tsx`),
    `/**
 * Derived from @ultraviolet/illustrations ${file} (Scaleway, Apache-2.0).
 * Fills rewritten to currentColor. Generated — do not edit by hand.
 */
import type { CSSProperties } from "react";

export const ${component}: React.FC<{
  readonly size?: number;
  readonly style?: CSSProperties;
}> = ({ size = 550, style }) => (
  <svg
    fill="none"
    height={size}
    style={style}
    viewBox="0 0 550 550"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
  >
    ${body}
  </svg>
);
`,
    "utf8",
  );

  emitted.push(component);
}

writeFileSync(
  join(OUT, "index.ts"),
  `/** Generated by scripts/build-illustrations.ts — do not edit by hand. */\n${emitted
    .map((c) => `export { ${c} } from "./${c}";`)
    .join("\n")}\n`,
  "utf8",
);

console.log(`Wrote ${emitted.length} illustration components`);
