/** Generated by scripts/build-illustrations.ts — do not edit by hand. */
export { ObjectStorageIllustration } from "./ObjectStorageIllustration";
export { BlockStorageIllustration } from "./BlockStorageIllustration";
export { InferenceIllustration } from "./InferenceIllustration";
