export { buildCoverSlide } from './cover'
export type { CoverSlideData } from './cover'
export { buildRisksSlide } from './risks'
export type { RisksSlideData } from './risks'
export { buildPricingSlide } from './pricing'
export type { PricingSlideData } from './pricing'
export { buildUsageChartSlide } from './usageChart'
export type { UsageChartSlideData } from './usageChart'
export { buildRoadmapSlide } from './roadmap'
export type { RoadmapSlideData } from './roadmap'
